services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-nginx
    ports:
      - "127.0.0.1:8280:80"
    networks:
      - portfolio_net
    restart: always

networks:
  portfolio_net:
    name: portfolio_net
